# Generated by Django 2.2.7 on 2020-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'blog_list',
            },
        ),
    ]
